# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-29 12:39+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: api/serializers/entry.py:127
msgid "will not be published"
msgstr ""

#: api/serializers/relation.py:23
msgid "Relation already exists"
msgstr ""

#: api/serializers/relation.py:30 api/views.py:187
msgid "Current user is not the owner of this entry"
msgstr ""

#: api/views.py:191 api/views.py:776 api/views.py:805
#: media_server/serializers.py:30
msgid "Entry does not exist"
msgstr ""

#: api/views.py:272
msgid "Schema not found for the given query"
msgstr ""

#: api/views.py:311 api/views.py:771
msgid "User does not exist"
msgstr ""

#: core/models.py:143
#, python-format
msgid "Type %(type_source)s does not belong to any active schema"
msgstr ""

#: core/models.py:150
#, python-format
msgid "Invalid data: %(error)s"
msgstr ""

#: core/models.py:153
msgid "Data without type"
msgstr ""

#: core/models.py:189
msgid "Both entries must belong to the same user"
msgstr ""

#: core/schemas/__init__.py:26
msgid "Schemas improperly configured"
msgstr ""

#: core/schemas/__init__.py:64
msgid "Active schemas contain duplicate types"
msgstr ""

#: core/schemas/entries/exhibition.py:45 core/schemas/general.py:100
#: core/schemas/general.py:116 core/schemas/general.py:150
#: core/schemas/general.py:173 core/schemas/general.py:189
#: core/schemas/general.py:210 core/schemas/general.py:232
msgid "and"
msgstr ""

#: core/utils.py:6
#, python-format
msgid "Enter %(label)s"
msgstr ""

#: core/validators.py:15
#, python-format
msgid "Invalid type: %(error)s"
msgstr ""

#: core/validators.py:23
msgid "Keywords contains duplicate entries"
msgstr ""

#: core/validators.py:25
#, python-format
msgid "Invalid keywords: %(error)s"
msgstr ""

#: core/validators.py:39
msgid "Same language is defined multiple times"
msgstr ""

#: core/validators.py:41
#, python-format
msgid "Invalid texts: %(error)s"
msgstr ""

#: media_server/archiver/controller/default.py:61
msgid "empty"
msgstr ""

#. Translators: Something goes wrong and the media for archival is not found.
#: media_server/archiver/messages/errors.py:4
msgid "Media assets do not exist"
msgstr ""

#. Translators: Only media assets of one entry can be archived together. 0 or more than one found
#: media_server/archiver/messages/errors.py:9
#, python-format
msgid "All media objects must belong to one entry. %(n_entries)d found"
msgstr ""

#. Translators: Something goes wrong and the user tried to archive an media asset, which he does not "own"
#: media_server/archiver/messages/errors.py:13 media_server/views.py:101
#: media_server/views.py:182 media_server/views.py:227
msgid "Current user is not the owner of this media object"
msgstr ""

#. Translators: The archival service is unavailable due to unknown reasons
#: media_server/archiver/messages/errors.py:18
#, python-format
msgid "%(service)s temporarily unavailable, try again later."
msgstr ""

#: media_server/archiver/messages/success.py:5
#, python-format
msgid ""
"Successfully %(modification_type)s %(object_description)s to %(service)s"
msgstr ""

#. Translators: Default message for fields with no value
#: media_server/archiver/messages/validation/__init__.py:6
msgid "Field may not be null."
msgstr ""

#. Translators: Default message for empty required fields
#: media_server/archiver/messages/validation/__init__.py:9
msgid "Missing data for required field."
msgstr ""

#. Translators: Default message for invalid type, for example a number is requested and en e-mail-address is given
#: media_server/archiver/messages/validation/__init__.py:12
msgid "Invalid type."
msgstr ""

#. Translators: Default message, when validation failed to unknown reason
#: media_server/archiver/messages/validation/__init__.py:15
msgid "Invalid value."
msgstr ""

#. Translators: Displayed, when missing an author
#: media_server/archiver/messages/validation/thesis.py:4
msgid "An author is required"
msgstr ""

#. Translators: Displayed, when missing language
#: media_server/archiver/messages/validation/thesis.py:8
msgid "Language is required"
msgstr ""

#. Translators: Displayed, when missing Supervisor
#: media_server/archiver/messages/validation/thesis.py:11
msgid "A supervisor is required"
msgstr ""

#. Translators: Displayed, when missing an English abstract
#: media_server/archiver/messages/validation/thesis.py:14
msgid "An English Abstract is required"
msgstr ""

#. Translators: Displayed, when missing a German abstract
#: media_server/archiver/messages/validation/thesis.py:17
msgid "A German Abstract is required"
msgstr ""

#: media_server/serializers.py:33
msgid "Current user is not the owner of entry"
msgstr ""

#: media_server/validators.py:17
#, python-format
msgid "Invalid license: %(error)s"
msgstr ""

#: media_server/validators.py:22
msgid "Invalid license"
msgstr ""

#: media_server/views.py:114 media_server/views.py:190
#: media_server/views.py:235
msgid "Media object does not exist"
msgstr ""

#: media_server/views.py:132
msgid "No space left for user"
msgstr ""

#: media_server/views.py:251
msgid "Asset validation successful"
msgstr ""

#: portfolio/settings.py:250
msgid "German"
msgstr ""

#: portfolio/settings.py:251
msgid "English"
msgstr ""
