# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-10-21 13:03+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: api/serializers/entry.py:139
msgid "will not be published"
msgstr ""

#: api/serializers/relation.py:23
msgid "Relation already exists"
msgstr ""

#: api/serializers/relation.py:30 api/views.py:195 api/views.py:225
msgid "Current user is not the owner of this entry"
msgstr ""

#: api/views.py:199 api/views.py:232 api/views.py:1048 api/views.py:1077
#: media_server/serializers.py:38
msgid "Entry does not exist"
msgstr ""

#: api/views.py:313
msgid "Schema not found for the given query"
msgstr ""

#: api/views.py:354 api/views.py:1043
msgid "User does not exist"
msgstr ""

#: core/models.py:121
#, python-format
msgid "Type %(type_source)s does not belong to any active schema"
msgstr ""

#: core/models.py:128
#, python-format
msgid "Invalid data: %(error)s"
msgstr ""

#: core/models.py:131
msgid "Data without type"
msgstr ""

#: core/models.py:167
msgid "Both entries must belong to the same user"
msgstr ""

#: core/schemas/__init__.py:26
msgid "Schemas improperly configured"
msgstr ""

#: core/schemas/__init__.py:64
msgid "Active schemas contain duplicate types"
msgstr ""

#: core/schemas/entries/exhibition.py:45 core/schemas/general.py:100
#: core/schemas/general.py:116 core/schemas/general.py:150
#: core/schemas/general.py:173 core/schemas/general.py:189
#: core/schemas/general.py:210 core/schemas/general.py:232
msgid "and"
msgstr ""

#: core/utils.py:6
#, python-format
msgid "Enter %(label)s"
msgstr ""

#: core/validators.py:15
#, python-format
msgid "Invalid type: %(error)s"
msgstr ""

#: core/validators.py:23
msgid "Keywords contains duplicate entries"
msgstr ""

#: core/validators.py:25
#, python-format
msgid "Invalid keywords: %(error)s"
msgstr ""

#: core/validators.py:39
msgid "Same language is defined multiple times"
msgstr ""

#: core/validators.py:41
#, python-format
msgid "Invalid texts: %(error)s"
msgstr ""

#: media_server/clamav.py:36
msgid "File is infected with malware"
msgstr ""

#: media_server/serializers.py:41
msgid "Current user is not the owner of entry"
msgstr ""

#: media_server/validators.py:17
#, python-format
msgid "Invalid license: %(error)s"
msgstr ""

#: media_server/validators.py:22
msgid "Invalid license"
msgstr ""

#: media_server/views.py:115 media_server/views.py:201
#: media_server/views.py:246
msgid "Current user is not the owner of this media object"
msgstr ""

#: media_server/views.py:133 media_server/views.py:209
#: media_server/views.py:254
msgid "Media object does not exist"
msgstr ""

#: media_server/views.py:151
msgid "No space left for user"
msgstr ""

#: portfolio/settings.py:250
msgid "German"
msgstr ""

#: portfolio/settings.py:251
msgid "English"
msgstr ""
